### ISSUE TITLE
Отрисовка на едином холсте

### ISSUE THREAD

**Issue by lonelyfox-dev** [lonelyfox-dev/graphics#2]
Крч я так и не нашёл способа отрисовывать все изменения на одном холсте и уже выгорел после поиска. Но возможно ты на свежем взгляде что-нибудь найдёшь. Сильно корпеть думаю не стоит, в крайнем случае назовём фичей и сошлёмся на особенности выбранного граф. пакета.

**Comment by SHTYKOVYCH** [comment]
Хей йо, кинул отрисовку в одном окне тебе за origin, проверяй
